package exception1;

public class Throw_Ex2 {
	public void test() throws ArithmeticException {
		Test t = new Test();
		t.input();
	}
}
